### ISSUE TITLE
Risk Parity Portfolio Tutorial Crashes When Using Mosek 8.1

### ISSUE THREAD

**Issue by zhoujs93** [MOSEK/Tutorials#3]
Is the code modified to only run on version 7.1 only ? I am running Python3 with Mosek 8.1 but everytime I run the notebook, the kernel seems to die. Is there any reason for this ?

**Comment by aszekMosek** [comment]
Hi.

Could you write what error appears and where? 

The whole SCOPT interface is going away soon so I would recommend not spending too much time on it. This whole notebook will be replaced with a new version.

**Comment by aszekMosek** [comment]
This version of the notebook demonstrates how the logarithmic terms will be expressed using the exponential cone in version 9:

https://github.com/MOSEK/Tutorials/blob/version9/portfolio-riskparity/riskparity.ipynb

**Comment by andreacassioli** [comment]
That's very cool! With more cones Fusion really shines....
