### ISSUE TITLE
Minimum ellipsoid example - how to adapt into an ellipsoid from the circle equation

### ISSUE THREAD

**Issue by rmsandu** [MOSEK/Tutorials#4]
Hello,

I was looking at this tutorial https://github.com/MOSEK/Tutorials/blob/master/minimum-ellipsoid/minimum-ellipsoid.ipynb that describes how to fit a circle around a set of points.

however, I was wondering how should I adapt the code to fit an ellipse around a set of points?

Moreover, ellipsoid refers to a 3D set of points. Would it be possible to use this example to fit an ellipse around points in the (x, y, z) space?

Thank you in advance :)

**Comment by aszekMosek** [comment]
See for example https://docs.mosek.com/9.1/pythonfusion/case-studies-ellipsoids.html#doc-fusion-case-studies-ellipsoids

**Comment by rmsandu** [comment]
Thank you for the answer.

I checked the code for the Lowner-John ellipsoids, but it fails given the same input data that works on this minimum enclosing sphere example from the Jupyter Notebook. So I can fit a sphere on my points, but not an ellipse (using your code). 
The optimization problem also seems to be set differently.

**Comment by aszekMosek** [comment]
If something fails please write to support@mosek.com with an example and explain what the problem is, or alternatively post the issue at the google group https://groups.google.com/forum/#!forum/mosek
